services:
  mysql:
    image: mysql:8.3
    container_name: p4_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jsp_project4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  tomcat:
    build:
      context: ./app
    container_name: p4_tomcat
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
